const masterType = {
  WORKINGSLOTS: 'WORKINGSLOTS',
  ADDWORKINGSLOTS: 'ADDWORKINGSLOTS',
  DELETEWORKINGSLOTS: 'DELETEWORKINGSLOTS',
  EDITWORKINGSLOTS: 'EDITWORKINGSLOTS'
}

export default masterType
